name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions: {}

jobs:
  release:
    name: Centrally verify, sign, and publish
    permissions:
      contents: write
    uses: spice-framework/.github/.github/workflows/library-release.yml@f436da76e19f26bb359e6173e4e16ba6ce53478d
    with:
      module: github.com/spice-framework/starter-oidc
